language: java

sudo: false

services:
- docker

cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && cd ./java && mvn deploy"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
