language: java

sudo: false

services:
- docker

deploy:
  provider: script
  script: "cd java && mvn deploy -s ../.travis.settings.xml"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
